export const apiUrls = {
  allies: {
    create: "/allies/create",
    update: "/allies/update",
    getAll: "/allies",
    delete: "/allies/delete",
  },
  auth: {
    loginByEmail: "/users/login-by-email",
    me: "/users/me",
  },
  petShops: {
    create: "/users/petshops/create",
    getAll: "/users/petshops",
    getByUser: "/users/petshops/by-user",
    getById: "/users/petshops",
    update: "/users/petshops/update",
    delete: "/users/petshops/delete",
    getInventory: "/products/inventories/by-petshop",
  },
  especies: {
    getAll: "/pets/species",
    create: "/pets/species/create",
    update: "/pets/species/update",
    delete: "/pets/species/delete",
  },
  characteristics: {
    getAll: "/pets/characteristics",
    create: "/pets/characteristics/create",
    update: "/pets/characteristics/update",
    delete: "/pets/characteristics/delete",
  },
  razas: {
    getAllBySpecieId: "/pets/breeds",
    create: "/pets/breeds/create",
    update: "/pets/breeds/update",
    delete: "/pets/breeds/delete",
  },
  atributos: {
    create: "/products/attributes/create",
    update: "/products/attributes/update",
    getAll: "/products/attributes",
    getAllById: "/products/attributes",
    delete: "/products/attributes/delete",
  },
  opciones_atributos: {
    create: "/products/attributes-options/create",
    update: "/products/attributes-options/update",
    getAllByOptionAttributeId: "/products/attributes-options/by-attribute",
    getAllByAttributeId: "/products/attributes-options",
    delete: "/products/attributes-options/delete",
  },
  categorias: {
    create: "/products/categories/create",
    update: "/products/categories/update",
    getAll: "/products/categories",
    delete: "/products/categories/delete",
  },
  marcas: {
    create: "/products/brands/create",
    update: "/products/brands/update",
    getAll: "/products/brands",
    getById: "/products/brands",
    delete: "/products/brands/delete",
  },
  condiciones: {
    create: "/pets/conditions/create",
    update: "/pets/conditions/update",
    getAll: "/pets/conditions",
    delete: "/pets/conditions/delete",
  },
  productos: {
    create: "/products/create",
    update: "/products/update",
    getAll: "/products",
    getById: "/products/product",
    filterAll: "/products/filter",
    delete: "/products/delete",
  },

  users: {
    create: "/users/create",
    update: "/users/update",
    getAll: "/users",
    delete: "/users/delete",
  },
  pedidos: {
    create: "/transactions/orders/create",
    getAll: "/transactions/orders",
    getById: "/transactions/orders",
    update: "/transactions/orders/update",
    delete: "/transactions/orders/delete",
  },
  solicitudesSurtidos: {
    create: "/transactions/orders/create",
    getAll: "/transactions/orders",
    getById: "/transactions/orders",
    update: "/transactions/orders/update",
    delete: "/transactions/orders/delete",
  },
  solicitudesRestock: {
    create: "/products/restock-request/create",
    getAll: "/products/restock-request/all",
    updateStatus: "/products/restock-request/update-status",
    bulkDelete: "/products/restock-request/bulk-delete",
  },
  gestionPagos: {
    create: "/transactions/petshop-payments/create",
    getAll: "/transactions/petshop-payments/all",
    update: "/transactions/petshop-payments",
  },
  pets: {
    create: "/pets/create",
    getAll: "/pets/all",
    update: "/pets/update",
    delete: "/pets/delete",
  },
};
