export const apiUrls = {
  merchants: {
    create: "/merchants/create",
    update: "/merchants/update",
    getAll: "/merchants/all",
    getOne: "/merchants/one",
  },
  branches: {
    create: "/branches/create",
    update: "/branches/update",
    getByMerchant: "/branches/by-merchant",
    search: "/branches/search",
    getOne: "/branches/one",
    delete: "/branches/delete",
  },
  categories: {
    create: "/categories/create",
    update: "/categories/update",
    getAll: "/categories/all",
    getOne: "/categories/one",
    delete: "/categories/delete",
  },
  auth: {
    loginByEmail: "/auth/login-by-email",
    me: "/auth/me",
  },
  users: {
    register: "/users/register",
    getAll: "/users/all",
    getOne: "/users/one",
    update: "/users/update",
    delete: "/users/delete",
    getByRole: "/users/by-role",
    deactivateAccount: "/users/deactivate-account",
  },
  membershipPlans: {
    create: "/memberships/plans/create",
    getAll: "/memberships/plans/all",
    getOne: "/memberships/plans/one",
  },
  coupons: {
    create: "/coupons/create",
    getAll: "/coupons/all",
    getOne: "/coupons/one",
    update: "/coupons/update",
    delete: "/coupons/delete",
  },
  offers: {
    create: "/offers/create",
    getAll: "/offers/all",
    getOne: "/offers/one",
    update: "/offers/update",
    delete: "/offers/delete",
  },
  files: {
    generatePresignedUrls: "/files/generate-presigned-urls",
  },
  redemptions: {
    create: "/redemptions/create",
    getAll: "/redemptions/all",
    getByMe: "/redemptions/by-me",
    getGenerated: "/redemptions/codes/generated",
    getUsed: "/redemptions/codes/used",
    metrics: "/redemptions/metrics",
  },
  gifts: {
    create: "/gifts/admin/create",
    getAll: "/gifts/admin/all",
    getOne: "/gifts/admin/one",
    update: "/gifts/admin/update",
    delete: "/gifts/admin/delete",
  },
};
